config/routes.rb
Rails.application.routes.draw do
  resources :skills
  resources :workers
  resources :vacancies
  resources :worker_skills
  resources :vacancy_skills
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'main', to: 'main#index', as: :main
  get '/workers/:id/vacancies', to: 'workers#vacancies'
  get '/vacancies/:id/workers', to: 'vacancies#workers'
  root :to => 'main#index'
end

app/models/vacancy.rb
class Vacancy < ApplicationRecord
  has_many :vacancy_skills
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  before_action :set_vacancy, only: [:show, :edit, :update, :destroy]

  # GET /vacancies
  # GET /vacancies.json
  def index
    @vacancies = Vacancy.all
  end

  # GET /vacancies/1
  # GET /vacancies/1.json
  def show
  end

  # GET /vacancies/new
  def new
    @vacancy = Vacancy.new
  end

  # GET /vacancies/1/edit
  def edit
  end

  def workers
    @vacancy = Vacancy.find(params[:id])
    @workers = find_a_suitable_workers(@vacancy)
    @partially_workers = find_a_partially_suitable_workers(@vacancy) - find_a_suitable_workers(@vacancy)
  end

  # POST /vacancies
  # POST /vacancies.json
  def create
    @vacancy = Vacancy.new(vacancy_params)

    respond_to do |format|
      if @vacancy.save
        format.html { redirect_to @vacancy, notice: 'Vacancy was successfully created.' }
        format.json { render :show, status: :created, location: @vacancy }
      else
        format.html { render :new }
        format.json { render json: @vacancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacancies/1
  # PATCH/PUT /vacancies/1.json
  def update
    respond_to do |format|
      if @vacancy.update(vacancy_params)
        format.html { redirect_to @vacancy, notice: 'Vacancy was successfully updated.' }
        format.json { render :show, status: :ok, location: @vacancy }
      else
        format.html { render :edit }
        format.json { render json: @vacancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacancies/1
  # DELETE /vacancies/1.json
  def destroy
    @vacancy.destroy
    respond_to do |format|
      format.html { redirect_to vacancies_url, notice: 'Vacancy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacancy
      @vacancy = Vacancy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vacancy_params
      params.require(:vacancy).permit(:name, :addition_date, :duration, :salary, :contact)
    end

    #
    # Работники полностью подходящие по скиллам
    #
    def find_a_suitable_workers(vacancy)
      workers = Array.new
      Worker.all.each do |w|
        workers << w if (get_worker_skills(w) &
            get_vacancy_skills(vacancy)).count == get_vacancy_skills(vacancy).count
      end
      in_search(workers)
    end

    #
    # Работники частично подходящие по скиллам
    #
    def find_a_partially_suitable_workers(vacancy)
      workers = Array.new
      Worker.all.each do |w|
        workers << w if (get_worker_skills(w) & get_vacancy_skills(vacancy)).count > 0
      end
      in_search(workers)
    end

    #
    # Метод для получения всех скиллов для вакансии
    #
    def get_vacancy_skills(vacancy)
      skills = Array.new
      vacancy.vacancy_skills.each do |skill|
        skills << skill.name
      end
      skills
    end

    #
    # Метод для получения всех скиллов работника
    #
    def get_worker_skills(worker)
      skills = Array.new
      worker.worker_skills.each do |skill|
        skills << skill.name
      end
      skills
    end

    #
    # Метод вернёт только работников, которые ищут работу
    #
    def in_search(workers)
      w = workers.select { |item| item.in_search}
      # Сортируем по зарплатным ожиданиям
      w.sort_by! { |wor| wor.salary }
    end

end

app/helpers/vacancies_helper.rb
module VacanciesHelper
end

app/views/vacancies/_form.html.erb
<%= form_for(vacancy) do |f| %>
  <% if vacancy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vacancy.errors.count, "error") %> prohibited this vacancy from being saved:</h2>

      <ul>
      <% vacancy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :addition_date %>
    <%= f.datetime_select :addition_date %>
  </div>

  <div class="field">
    <%= f.label :duration %>
    <%= f.datetime_select :duration %>
  </div>

  <div class="field">
    <%= f.label :salary %>
    <%= f.number_field :salary %>
  </div>

  <div class="field">
    <%= f.label :contact %>
    <%= f.text_area :contact %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vacancies/_form_skill.html.erb
<%= form_tag '/vacancy_skills' do %>
    <% options = Array.new %>
    <% Skill.all.each do |skill| %>
        <% options << [skill.name, skill.id] %>
    <% end %>
    <%= select_tag(:skill_id, options_for_select(options)) %>
    <%= hidden_field_tag(:vacancy_id, @vacancy.id) %>
    <%= submit_tag 'Add' %>
<% end %>

app/views/vacancies/edit.html.erb
<h1>Editing Vacancy</h1>

<%= render 'form_skill', vacancy: @vacancy %>
<%= render 'form', vacancy: @vacancy %>

<%= link_to 'Show', @vacancy %> |
<%= link_to 'Back', vacancies_path %>

app/views/vacancies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vacancies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Addition date</th>
      <th>Duration</th>
      <th>Salary</th>
      <th>Contact</th>
      <th>Skills</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vacancies.each do |vacancy| %>
      <tr>
        <td><%= vacancy.name %></td>
        <td><%= vacancy.addition_date %></td>
        <td><%= vacancy.duration %></td>
        <td><%= vacancy.salary %></td>
        <td><%= vacancy.contact %></td>
        <td><%= vacancy.vacancy_skills.map {|skill| skill.name}%></td>
        <td><%= link_to 'workers', controller: 'vacancies', action: 'workers', id: vacancy.id %></td>
        <td><%= link_to 'Show', vacancy %></td>
        <td><%= link_to 'Edit', edit_vacancy_path(vacancy) %></td>
        <td><%= link_to 'Destroy', vacancy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vacancy', new_vacancy_path %>

app/views/vacancies/new.html.erb
<h1>New Vacancy</h1>

<%= render 'form', vacancy: @vacancy %>

<%= link_to 'Back', vacancies_path %>

app/views/vacancies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vacancy.name %>
</p>

<p>
  <strong>Addition date:</strong>
  <%= @vacancy.addition_date %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @vacancy.duration %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @vacancy.salary %>
</p>

<p>
  <strong>Skills:</strong>
  <% @vacancy.vacancy_skills.each do |skill| %>
      <br><%= skill.name %>
  <% end %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @vacancy.contact %>
</p>

<%= link_to 'Edit', edit_vacancy_path(@vacancy) %> |
<%= link_to 'Back', vacancies_path %>

app/views/vacancies/workers.html.erb
<h1>Текущая вакансия :</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Addition date</th>
    <th>Duration</th>
    <th>Salary</th>
    <th>Contact</th>
    <th>Skills</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @vacancy.name %></td>
        <td><%= @vacancy.addition_date %></td>
        <td><%= @vacancy.duration %></td>
        <td><%= @vacancy.salary %></td>
        <td><%= @vacancy.contact %></td>
        <td><%= @vacancy.vacancy_skills.map {|skill| skill.name}%></td>
      </tr>
  </tbody>
</table>

<br>

<h1>Подходящие работники :</h1>
<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Contact</th>
    <th>In search</th>
    <th>Salary</th>
    <th>Skills</th>>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @workers.each do |worker| %>
      <tr>
        <td><%= worker.name %></td>
        <td><%= worker.contact %></td>
        <td><%= worker.in_search %></td>
        <td><%= worker.salary %></td>
        <td><%= worker.worker_skills.map {|skill| skill.name}%></td>
      </tr>
  <% end %>
  </tbody>

</table>

<br>

<h1>Частично подходящие работники :</h1>
<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Contact</th>
    <th>In search</th>
    <th>Salary</th>
    <th>Skills</th>>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @partially_workers.each do |worker| %>
      <tr>
        <td><%= worker.name %></td>
        <td><%= worker.contact %></td>
        <td><%= worker.in_search %></td>
        <td><%= worker.salary %></td>
        <td><%= worker.worker_skills.map {|skill| skill.name}%></td>
      </tr>
  <% end %>
  </tbody>

</table>

<br>