config/routes.rb
Rails.application.routes.draw do
  resources :skills
  resources :workers
  resources :vacancies
  resources :worker_skills
  resources :vacancy_skills
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'main', to: 'main#index', as: :main
  get '/workers/:id/vacancies', to: 'workers#vacancies'
  get '/vacancies/:id/workers', to: 'vacancies#workers'
  root :to => 'main#index'
end

app/models/worker.rb
class Worker < ApplicationRecord
  has_many :worker_skills, dependent: :destroy
  validates :name, :contact, presence: true
  validates :name, format: {
      with: %r{[А-ЯЁ][а-яё]+ [А-ЯЁ][а-яё]+ [А-ЯЁ][а-яё]+},
      message: 'Имя должно состоять из 3-х слов на кириллице'
  }
  validates :contact, format: {
      with: %r{([-\w.]+@([A-z0-9][-A-z0-9]+\.)+[A-z]{2,4})|(((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,10})},
      message: 'Отсутствует почта или телефон'
  }
  validates :salary, numericality: {greater_than: 0}

end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]

  # GET /workers
  # GET /workers.json
  def index
    @workers = Worker.all
  end

  # GET /workers/1
  # GET /workers/1.json
  def show
  end

  # GET /workers/new
  def new
    @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
    @worker_skill = WorkerSkill.new
  end

  def vacancies
    @worker = Worker.find(params[:id])
    @vacancies = find_a_suitable_job(@worker)
    @partially_vacancies = find_a_partially_suitable_job(@worker) - find_a_suitable_job(@worker)
  end

  # POST /workers
  # POST /workers.json
  def create
    @worker = Worker.new(worker_params)

    respond_to do |format|
      if @worker.save
        format.html { redirect_to @worker, notice: 'Worker was successfully created.' }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers/1
  # PATCH/PUT /workers/1.json
  def update
    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to @worker, notice: 'Worker was successfully updated.' }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1
  # DELETE /workers/1.json
  def destroy
    @worker.destroy
    respond_to do |format|
      format.html { redirect_to workers_url, notice: 'Worker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worker_params
      params.require(:worker).permit(:name, :contact, :in_search, :salary)
    end

    #
    # Метод вернёт все подходящие вакансии для работника
    #
    def find_a_suitable_job(worker)
      vacancies = Array.new
      Vacancy.all.each do |v|
        vacancies << v if (get_vacancy_skills(v) &
            get_worker_skills(worker)).count == get_vacancy_skills(v).count
      end
      # Убираем из выдачи те вакансии, что истекли по дате
      not_expired(vacancies)
    end

    #
    # Частично подходящие вакансии
    #
    def find_a_partially_suitable_job(worker)
      vacancies = Array.new
      Vacancy.all.each do |v|
        vacancies << v if (get_worker_skills(worker) & get_vacancy_skills(v)).count > 0
      end
      # Убираем из выдачи те вакансии, что истекли по дате
      not_expired(vacancies)
    end


    #
    # Метод для получения всех скиллов для вакансии
    #
    def get_vacancy_skills(vacancy)
      skills = Array.new
      vacancy.vacancy_skills.each do |skill|
        skills << skill.name
      end
      skills
    end

    #
    # Метод для получения всех скиллов работника
    #
    def get_worker_skills(worker)
      skills = Array.new
      worker.worker_skills.each do |skill|
        skills << skill.name
      end
      skills
    end

    #
    # отдаём вакансии, которые не истекли по времени
    #
    def not_expired(vacancies)
      v = vacancies.select { |item| item.duration > Time.now }
      # Сортируем по размеру заработной платы
      v.sort_by! { |vac| vac.salary }
    end

end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/workers/_form.html.erb
<%= form_for(worker) do |f| %>
  <% if worker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(worker.errors.count, "error") %> prohibited this worker from being saved:</h2>

      <ul>
      <% worker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :contact %>
    <%= f.text_area :contact %>
  </div>

  <div class="field">
    <%= f.label :in_search %>
    <%= f.check_box :in_search %>
  </div>

  <div class="field">
    <%= f.label :salary %>
    <%= f.number_field :salary %>
  </div>

  <div class="field">
    <%= f.label :skill %>
    <%= f.collection_select :worker_id, Skill.all, :id, :name, prompt: true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workers/_form_skill.html.erb
<%= form_tag '/worker_skills' do %>
    <% options = Array.new %>
    <% Skill.all.each do |skill| %>
    <% options << [skill.name, skill.id] %>
    <% end %>
    <%= select_tag(:skill_id, options_for_select(options)) %>
    <%= hidden_field_tag(:worker_id, @worker.id) %>
    <%= submit_tag 'Add' %>
<% end %>

app/views/workers/edit.html.erb
<h1>Editing Worker</h1>

<%= render 'form_skill', worker: @worker %>
<%= render 'form', worker: @worker %>


<%= link_to 'Show', @worker %> |
<%= link_to 'Back', workers_path %>

app/views/workers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Workers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Contact</th>
      <th>In search</th>
      <th>Salary</th>
      <th>Skills</th>>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workers.each do |worker| %>
      <tr>
        <td><%= worker.name %></td>
        <td><%= worker.contact %></td>
        <td><%= worker.in_search %></td>
        <td><%= worker.salary %></td>
        <td><%= worker.worker_skills.map {|skill| skill.name}%></td>
        <td><%= link_to 'vacancies', controller: 'workers', action: 'vacancies', id: worker.id %></td>
        <td><%= link_to 'Show', worker %></td>
        <td><%= link_to 'Edit', edit_worker_path(worker) %></td>
        <td><%= link_to 'Destroy', worker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Worker', new_worker_path %>

app/views/workers/new.html.erb
<h1>New Worker</h1>

<%= render 'form', worker: @worker %>

<%= link_to 'Back', workers_path %>

app/views/workers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @worker.name %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @worker.contact %>
</p>

<p>
  <strong>In search:</strong>
  <%= @worker.in_search %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @worker.salary %>
</p>

<p id="skills">
  <strong>Skills:</strong>
  <% @worker.worker_skills.each do |skill| %>
  <br><%= skill.name %>
  <% end %>
</p>

<%= link_to 'Edit', edit_worker_path(@worker) %> |
<%= link_to 'Back', workers_path %>

app/views/workers/vacancies.html.erb
<h1>Текущий работник :</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Contact</th>
    <th>In search</th>
    <th>Salary</th>
    <th>Skills</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @worker.name %></td>
        <td><%= @worker.contact %></td>
        <td><%= @worker.in_search %></td>
        <td><%= @worker.salary %></td>
        <td><%= @worker.worker_skills.map {|skill| skill.name} %></td>
      </tr>
  </tbody>
</table>

<br>

<h1>Подходящие вакансии :</h1>
<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Duration</th>
    <th>Salary</th>
    <th>Contact</th>
    <th>Skills</th>
  </tr>
  </thead>

  <tbody>
  <% @vacancies.each do |vacancy| %>
      <tr>
        <td><%= vacancy.name %></td>
        <td><%= vacancy.duration %></td>
        <td><%= vacancy.salary %></td>
        <td><%= vacancy.contact %></td>
        <td><%= vacancy.vacancy_skills.map {|skill| skill.name} %></td>
      </tr>
  <% end %>
  </tbody>

</table>

<br>

<h1>Частично подходящие вакансии :</h1>
<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Duration</th>
    <th>Salary</th>
    <th>Contact</th>
    <th>Skills</th>
  </tr>
  </thead>

  <tbody>
  <% @partially_vacancies.each do |vacancy| %>
      <tr>
        <td><%= vacancy.name %></td>
        <td><%= vacancy.duration %></td>
        <td><%= vacancy.salary %></td>
        <td><%= vacancy.contact %></td>
        <td><%= vacancy.vacancy_skills.map {|skill| skill.name} %></td>
      </tr>
  <% end %>
  </tbody>

</table>

<br>